/*
 * self-managed-osdu
 * Rest API Documentation for Self Managed OSDU
 *
 * OpenAPI spec version: 0.11.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.22
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FileID'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FileID'));
  } else {
    // Browser globals (root is window)
    if (!root.SelfManagedOsdu) {
      root.SelfManagedOsdu = {};
    }
    root.SelfManagedOsdu.FileSourceLocationResponse = factory(root.SelfManagedOsdu.ApiClient, root.SelfManagedOsdu.FileID);
  }
}(this, function(ApiClient, FileID) {
  'use strict';

  /**
   * The FileSourceLocationResponse model module.
   * @module model/FileSourceLocationResponse
   * @version 0.11.0
   */

  /**
   * Constructs a new <code>FileSourceLocationResponse</code>.
   * @alias module:model/FileSourceLocationResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>FileSourceLocationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileSourceLocationResponse} obj Optional instance to populate.
   * @return {module:model/FileSourceLocationResponse} The populated <code>FileSourceLocationResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('FileID'))
        obj.fileID = FileID.constructFromObject(data['FileID']);
      if (data.hasOwnProperty('Location'))
        obj.location = ApiClient.convertToType(data['Location'], {'String': 'String'});
    }
    return obj;
  }

  /**
   * @member {module:model/FileID} fileID
   */
  exports.prototype.fileID = undefined;

  /**
   * @member {Object.<String, String>} location
   */
  exports.prototype.location = undefined;


  return exports;

}));
