/*
 * self-managed-osdu
 * Rest API Documentation for Self Managed OSDU
 *
 * OpenAPI spec version: 0.11.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.22
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SelfManagedOsdu) {
      root.SelfManagedOsdu = {};
    }
    root.SelfManagedOsdu.LegalTagInvalidResponse = factory(root.SelfManagedOsdu.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The LegalTagInvalidResponse model module.
   * @module model/LegalTagInvalidResponse
   * @version 0.11.0
   */

  /**
   * Constructs a new <code>LegalTagInvalidResponse</code>.
   * Represents a single invalid LegalTag.
   * @alias module:model/LegalTagInvalidResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>LegalTagInvalidResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LegalTagInvalidResponse} obj Optional instance to populate.
   * @return {module:model/LegalTagInvalidResponse} The populated <code>LegalTagInvalidResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('reason'))
        obj.reason = ApiClient.convertToType(data['reason'], 'String');
    }
    return obj;
  }

  /**
   * The name of the LegalTag.
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * The reason the LegalTag is currently invalid.
   * @member {String} reason
   */
  exports.prototype.reason = undefined;


  return exports;

}));
