/*
 * self-managed-osdu
 * Rest API Documentation for Self Managed OSDU
 *
 * OpenAPI spec version: 0.11.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.22
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RegisterDdmsInterface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RegisterDdmsInterface'));
  } else {
    // Browser globals (root is window)
    if (!root.SelfManagedOsdu) {
      root.SelfManagedOsdu = {};
    }
    root.SelfManagedOsdu.RegisterDdms = factory(root.SelfManagedOsdu.ApiClient, root.SelfManagedOsdu.RegisterDdmsInterface);
  }
}(this, function(ApiClient, RegisterDdmsInterface) {
  'use strict';

  /**
   * The RegisterDdms model module.
   * @module model/RegisterDdms
   * @version 0.11.0
   */

  /**
   * Constructs a new <code>RegisterDdms</code>.
   * @alias module:model/RegisterDdms
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RegisterDdms</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegisterDdms} obj Optional instance to populate.
   * @return {module:model/RegisterDdms} The populated <code>RegisterDdms</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('contactEmail'))
        obj.contactEmail = ApiClient.convertToType(data['contactEmail'], 'String');
      if (data.hasOwnProperty('interfaces'))
        obj.interfaces = ApiClient.convertToType(data['interfaces'], [RegisterDdmsInterface]);
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} contactEmail
   */
  exports.prototype.contactEmail = undefined;

  /**
   * @member {Array.<module:model/RegisterDdmsInterface>} interfaces
   */
  exports.prototype.interfaces = undefined;


  return exports;

}));
