/*
 * self-managed-osdu
 * Rest API Documentation for Self Managed OSDU
 *
 * OpenAPI spec version: 0.11.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.22
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SearchPoint'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SearchPoint'));
  } else {
    // Browser globals (root is window)
    if (!root.SelfManagedOsdu) {
      root.SelfManagedOsdu = {};
    }
    root.SelfManagedOsdu.SearchByDistance = factory(root.SelfManagedOsdu.ApiClient, root.SelfManagedOsdu.SearchPoint);
  }
}(this, function(ApiClient, SearchPoint) {
  'use strict';

  /**
   * The SearchByDistance model module.
   * @module model/SearchByDistance
   * @version 0.11.0
   */

  /**
   * Constructs a new <code>SearchByDistance</code>.
   * A spatial filter criteria to filter documents that exist within a specific distance from a geo point.
   * @alias module:model/SearchByDistance
   * @class
   * @param point {module:model/SearchPoint} 
   */
  var exports = function(point) {
    this.point = point;
  };

  /**
   * Constructs a <code>SearchByDistance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchByDistance} obj Optional instance to populate.
   * @return {module:model/SearchByDistance} The populated <code>SearchByDistance</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('distance'))
        obj.distance = ApiClient.convertToType(data['distance'], 'Number');
      if (data.hasOwnProperty('point'))
        obj.point = SearchPoint.constructFromObject(data['point']);
    }
    return obj;
  }

  /**
   * @member {Number} distance
   */
  exports.prototype.distance = undefined;

  /**
   * @member {module:model/SearchPoint} point
   */
  exports.prototype.point = undefined;


  return exports;

}));
