# -------HTTP REST CLIENT -------
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@login_base = login.microsoftonline.com/{{TENANT_ID}}
@oauth_token_host = {{login_base}}/oauth2/v2.0/token
@scopes = {{CLIENT_ID}}/.default openid profile offline_access
@AUTH_CODE = 0.ARoAv4j5cvGGr0GRqy180BHbR6qSYpjNLodNp9ziS5LlAbwaAAA.AQABAAIAAAD--DLA3VO7QrddgJg7WevrbTyM8N3wVtNnm0UA_gtPh2qNLR7Dwu4z1NLNc2_4jV9rMlJC_RhGN0ksnRlbgeVob7SmgkFPtHxZWjl8SxZzMm_x2WiH_TiobE2QmkkxCQkMAqq1GwGaNNnERlw3oITCPfHR7Hf846aiL5L3AjTesYlIhJW1KA7ECTgkHeo79Wuco16qyI1xDYkRpl5utf2CAgTJB2Oz9Iwp8-1qyBNZKtyQ9GqfOP3jDPZ0tnNiCFwXj2L5guIXbBBuELfCnyNfql1eRhmVV68AX5u-8kO0nILIKE_o9OFdwF5lhRTcOOZ3Gs71vV_dEnM47cosqMMaXyaGBfD1ogjsuCEaCeO2_Y7HE8KhoiL2D283g8MjyUFfQavWkJjJ0PQbj6RZVTpj3NbK7xifgXmFBPJV8wxqaZ3RcMo5bAl7OU_RZdy00eveAgSIHYBirpVGtgTATYhllY9D7zL5gp0qyPGtktCU9fpTY6NX-skWPgDcSm5VXvdVj2f3B1-EE4hefEjeLeXCN2_aQDtmrjnTYqzpsHv4VEqZSryR5xwT7ijh0oRv74CLobtxLfn6hdaaVkCls3m2rLacXdhRSx4Ks4qlrCXSnY14f6HzNSNPXwnwJfW6NUjeJxFBH3aEBGa_5sUnx1MT3NN8k7DabJHbfNeFQzsXZ0voDmm3dF-OfiIW5lsg_EZHfJW4606Z7BRmD07Gy24m84j_db1lo8HLp77JYNM7qQcbd92-yfz-8j8w0uWqQm1_2HGyhdzxR7xHVWz1H1U-IAA

# -----------------------
# OAUTH  authorization_code
# -----------------------
###
# @name authorize
POST https://{{oauth_token_host}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&redirect_uri=https://{{OSDU_HOST}}/login/
&client_id={{CLIENT_ID}}
&client_secret={{CLIENT_SECRET}}
&scope={{scopes}}
&code={{AUTH_CODE}}


# -----------------------
# OAUTH  refresh_token
# -----------------------
###
# @name refresh
POST https://{{oauth_token_host}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&client_id={{CLIENT_ID}}
&client_secret={{CLIENT_SECRET}}
&refresh_token={{authorize.response.body.refresh_token}}
&scope={{scopes}}


# -----------------------
# API (Variables)
# -----------------------
###
@access_token = {{refresh.response.body.access_token}}
