# -------HTTP REST CLIENT -------
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@login_base = login.microsoftonline.com/{{TENANT_ID}}
@oauth_token_host = {{login_base}}/oauth2/v2.0/token
@scopes = {{CLIENT_ID}}/.default openid profile offline_access
@AUTH_CODE = 0.ARoAv4j5cvGGr0GRqy180BHbR9y_c7U6VO9IsbgSY4e4tNYaANw.AQABAAIAAAD--DLA3VO7QrddgJg7WevrJs897GxhJDsVtSMOv9ga4LwUkZbFxiBVqo9EcMiyvZPid84mvSQwEEBlP0CzHzXOPsEoodlcFFwDV-42z0lsm-YT7CX8tXYX1gC0IEmGfbeZcqzTzHoFLX1tYYU9ATe-FrSNDww1E3Jb9prrSF_BWoiOOWp6wKZK5RehorjsWj_Ns5UYHaNs4hzZ2p87stp_bAwz_euDMA3HH39aObubgH4JDYtdEzsVjfzEmmOEe6Cps-GrugZ8ikh0kYScBIN_aVKnzNKdz_ogEe79C4js_DCYtlZkdyHs7Su_Z8JrRJt_HkaXZJKYowT_NPmXKZCVNu-r5CE7YpVDRSz9aNVp4QXUz1tIJzgHPvi1eTB280_fOu2VYH_7YH5FQ0Rnx9EicF4T7hhRhWp9aNAKnWS0_xE-DZgltLBmVIV0DqwgWhOh94X9eMt4LJDvS-7J2FEQ6u5lERGOY8EVbno4DTIkd8fsl6sX2-espRae2r7lre7ycV3LLuBeg26kjbiz67wZt1pPw5rYphUr5f_uc8IHh40ecpFTxTGNz3HityNhy9lkCqDif_GAoB5C625BSE-xShqtiZmlaxODNV7N9TXYCFD1GHG22iaSXhyXf65VDZ8_9-rf8515eSOIVH5Bk4MpADY3G81J5LQaMK6_jpty9dPuJDSDzVBSl05TaVHupoHq7_LsE3VKzwo6PpW9pGWqrr2acUXZpuJoFrkFnsIapq65CgvZFxQ9WzUmS2krqhLzeuRdgq8pu1z72rrvbYw9uV-ZmZWYzN9OtZwNO0bEzewqlQnVGLtoql3G9FsuR7giwH4AicbdPo5uFSZgp_Itvje2A9HyCfqBgjSnSL1XnuOdwtiSpp-CHuKdJ78PFX3wUng_A2RDebHtudAd7sbnIAA

# -----------------------
# OAUTH  authorization_code
# -----------------------
###
# @name authorize
POST https://{{oauth_token_host}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&redirect_uri=https://{{OSDU_HOST}}/login/
&client_id={{CLIENT_ID}}
&client_secret={{CLIENT_SECRET}}
&scope={{scopes}}
&code={{AUTH_CODE}}


# -----------------------
# OAUTH  refresh_token
# -----------------------
###
# @name refresh
POST https://{{oauth_token_host}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&client_id={{CLIENT_ID}}
&client_secret={{CLIENT_SECRET}}
&refresh_token={{authorize.response.body.refresh_token}}
&scope={{scopes}}


# -----------------------
# API (Variables)
# -----------------------
###
@access_token = {{refresh.response.body.access_token}}
