# coding: utf-8

"""
    self-managed-osdu

    Rest API Documentation for Self Managed OSDU  # noqa: E501

    OpenAPI spec version: 0.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from OsduClient.configuration import Configuration


class LegalTagDtos(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'legal_tags': 'list[LegalTagDto]'
    }

    attribute_map = {
        'legal_tags': 'legalTags'
    }

    def __init__(self, legal_tags=None, _configuration=None):  # noqa: E501
        """LegalTagDtos - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._legal_tags = None
        self.discriminator = None

        if legal_tags is not None:
            self.legal_tags = legal_tags

    @property
    def legal_tags(self):
        """Gets the legal_tags of this LegalTagDtos.  # noqa: E501

        A collection of complete LegalTags  # noqa: E501

        :return: The legal_tags of this LegalTagDtos.  # noqa: E501
        :rtype: list[LegalTagDto]
        """
        return self._legal_tags

    @legal_tags.setter
    def legal_tags(self, legal_tags):
        """Sets the legal_tags of this LegalTagDtos.

        A collection of complete LegalTags  # noqa: E501

        :param legal_tags: The legal_tags of this LegalTagDtos.  # noqa: E501
        :type: list[LegalTagDto]
        """

        self._legal_tags = legal_tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LegalTagDtos, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LegalTagDtos):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LegalTagDtos):
            return True

        return self.to_dict() != other.to_dict()
