---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-base
  namespace: default
spec:
  chart:
    spec:
      chart: ./osdu-base
      sourceRef:
        kind: GitRepository
        name: helm-charts-azure
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: default
  values:
    ingress:
      admin: "admin@self.managed.osdu.com"
