# coding: utf-8

"""
    self-managed-osdu

    Rest API Documentation for Self Managed OSDU  # noqa: E501

    OpenAPI spec version: 0.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class RegisterTopicExample(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'kind': 'str',
        'op': 'str'
    }

    attribute_map = {
        'id': 'id',
        'kind': 'kind',
        'op': 'op'
    }

    def __init__(self, id=None, kind=None, op=None, _configuration=None):  # noqa: E501
        """RegisterTopicExample - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._kind = None
        self._op = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if kind is not None:
            self.kind = kind
        if op is not None:
            self.op = op

    @property
    def id(self):
        """Gets the id of this RegisterTopicExample.  # noqa: E501


        :return: The id of this RegisterTopicExample.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RegisterTopicExample.


        :param id: The id of this RegisterTopicExample.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def kind(self):
        """Gets the kind of this RegisterTopicExample.  # noqa: E501


        :return: The kind of this RegisterTopicExample.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this RegisterTopicExample.


        :param kind: The kind of this RegisterTopicExample.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def op(self):
        """Gets the op of this RegisterTopicExample.  # noqa: E501


        :return: The op of this RegisterTopicExample.  # noqa: E501
        :rtype: str
        """
        return self._op

    @op.setter
    def op(self, op):
        """Sets the op of this RegisterTopicExample.


        :param op: The op of this RegisterTopicExample.  # noqa: E501
        :type: str
        """

        self._op = op

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RegisterTopicExample, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegisterTopicExample):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RegisterTopicExample):
            return True

        return self.to_dict() != other.to_dict()
