/*
 * self-managed-osdu
 * Rest API Documentation for Self Managed OSDU
 *
 * OpenAPI spec version: 0.11.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.22
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SelfManagedOsdu);
  }
}(this, function(expect, SelfManagedOsdu) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SelfManagedOsdu.FileServiceInternalApi();
  });

  describe('(package)', function() {
    describe('FileServiceInternalApi', function() {
      describe('allowsTheApplicationToAuditTheAttemptedFileUploadsTheMethodIsInternalAndIsNotAvailableForThirdPartyApplications_', function() {
        it('should call allowsTheApplicationToAuditTheAttemptedFileUploadsTheMethodIsInternalAndIsNotAvailableForThirdPartyApplications_ successfully', function(done) {
          // TODO: uncomment, update parameter values for allowsTheApplicationToAuditTheAttemptedFileUploadsTheMethodIsInternalAndIsNotAvailableForThirdPartyApplications_ call and complete the assertions
          /*
          var dataPartitionId = "dataPartitionId_example";
          var opts = {};
          opts.body = new SelfManagedOsdu.FileListRequest();
          opts.body.timeFrom = new SelfManagedOsdu.FileDateTime();
          opts.body.timeTo = new SelfManagedOsdu.FileDateTime();
          opts.body.pageNum = 0;
          opts.body.items = 0;
          opts.body.userID = "";

          instance.allowsTheApplicationToAuditTheAttemptedFileUploadsTheMethodIsInternalAndIsNotAvailableForThirdPartyApplications_(dataPartitionId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SelfManagedOsdu.FileListResponse);
            {
              let dataCtr = data.content;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(SelfManagedOsdu.FileLocation);
                expect(data.fileID).to.be.a(SelfManagedOsdu.FileID);
                    expect(data.driver).to.be.a(SelfManagedOsdu.FileDriver);
                    expect(data.location).to.be.a('string');
                expect(data.location).to.be("");
                expect(data.createdAt).to.be.a(Date);
                expect(data.createdAt).to.be(new Date());
                expect(data.createdBy).to.be.a('string');
                expect(data.createdBy).to.be("");

                      }
            }
            expect(data._number).to.be.a('number');
            expect(data._number).to.be(0);
            expect(data.numberOfElements).to.be.a('number');
            expect(data.numberOfElements).to.be(0);
            expect(data.size).to.be.a('number');
            expect(data.size).to.be(0);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('returnsFileLocationAndDriver_', function() {
        it('should call returnsFileLocationAndDriver_ successfully', function(done) {
          // TODO: uncomment, update parameter values for returnsFileLocationAndDriver_ call and complete the assertions
          /*
          var dataPartitionId = "dataPartitionId_example";
          var opts = {};
          opts.body = new SelfManagedOsdu.FileLocationRequest();
          opts.body.fileID = new SelfManagedOsdu.FileID();

          instance.returnsFileLocationAndDriver_(dataPartitionId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SelfManagedOsdu.FileLocationResponse);
            expect(data.driver).to.be.a(SelfManagedOsdu.FileDriver);
                expect(data.location).to.be.a('string');
            expect(data.location).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
