# This file contains the essential configs for the osdu on azure helm chart

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  targetPort: 8125

################################################################################
# Specify the azure environment specific values
#
azure:
  tenant: <tenant_id>
  subscription: <subscription_id>
  resourcegroup: <central_resource_group>
  identity: <identity_name>
  identity_id: <identity_id>
  keyvault: <keyvault_name>
  appid: <client_id>

################################################################################
# Specify any optional override values
#
image:
  repository: <registry_url>

################################################################################
# Specify pgbouncer configuration
#
pgbouncer:
  enabled: true
  port: 6543
  max_client_connections: 3000
  airflowdb:
    name: airflow
    host: <airflow_externalDatabase_host>
    port: 5432
    pool_size: 100
    user:  <airflow_externalDatabase_user>
    passwordSecret: "postgres"
    passwordSecretKey: "postgres-password"

