#  Copyright © Microsoft Corporation
#
apiVersion: v2
name: osdu-airflow-configure
type: application
description: Configures Airflow for OSDU"
appVersion: 1.0.0
version: 1.0.0
maintainers:
  - name: danielscholl
    url: https://github.com/danielscholl
