---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/sealed-secrets
  prune: true
  validation: client
  healthChecks:
    - kind: Deployment
      name: sealed-secrets
      namespace: kube-system
