/*
 * self-managed-osdu
 * Rest API Documentation for Self Managed OSDU
 *
 * OpenAPI spec version: 0.11.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.22
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SelfManagedOsdu);
  }
}(this, function(expect, SelfManagedOsdu) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('FileLandingZoneLocationResponse', function() {
      beforeEach(function() {
        instance = new SelfManagedOsdu.FileLandingZoneLocationResponse();
      });

      it('should create an instance of FileLandingZoneLocationResponse', function() {
        // TODO: update the code to test FileLandingZoneLocationResponse
        expect(instance).to.be.a(SelfManagedOsdu.FileLandingZoneLocationResponse);
      });

      it('should have the property fileID (base name: "FileID")', function() {
        // TODO: update the code to test the property fileID
        expect(instance).to.have.property('fileID');
        // expect(instance.fileID).to.be(expectedValueLiteral);
      });

      it('should have the property location (base name: "Location")', function() {
        // TODO: update the code to test the property location
        expect(instance).to.have.property('location');
        // expect(instance.location).to.be(expectedValueLiteral);
      });

    });
  });

}));
