apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: osdu-azure
resources:
  - namespace.yaml
  - self-managed-base.yaml
  - default-service.yaml
  - partition-service.yaml
  - entitlement-service.yaml
  - legal-service.yaml
  - storage-service.yaml
  - schema-service.yaml
  - file-service.yaml
  - dataset-service.yaml
  - indexer-service.yaml
  - indexer-queue.yaml
  - search-service.yaml
  - notification-service.yaml
  - register-service.yaml
  - unit-service.yaml
  - crs-catalog.yaml
  - crs-conversion.yaml
  - wks-service.yaml
  - workflow-service.yaml
