# coding: utf-8

"""
    self-managed-osdu

    Rest API Documentation for Self Managed OSDU  # noqa: E501

    OpenAPI spec version: 0.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import OsduClient
from OsduClient.models.register_filter import RegisterFilter  # noqa: E501
from OsduClient.rest import ApiException


class TestRegisterFilter(unittest.TestCase):
    """RegisterFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegisterFilter(self):
        """Test RegisterFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OsduClient.models.register_filter.RegisterFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
