# coding: utf-8

"""
    self-managed-osdu

    Rest API Documentation for Self Managed OSDU  # noqa: E501

    OpenAPI spec version: 0.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import OsduClient
from OsduClient.models.legal_tag_request import LegalTagRequest  # noqa: E501
from OsduClient.rest import ApiException


class TestLegalTagRequest(unittest.TestCase):
    """LegalTagRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLegalTagRequest(self):
        """Test LegalTagRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OsduClient.models.legal_tag_request.LegalTagRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
