# coding: utf-8

"""
    self-managed-osdu

    Rest API Documentation for Self Managed OSDU  # noqa: E501

    OpenAPI spec version: 0.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.legal_tag_properties import LegalTagProperties  # noqa: E501
from swagger_client.rest import ApiException


class TestLegalTagProperties(unittest.TestCase):
    """LegalTagProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLegalTagProperties(self):
        """Test LegalTagProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.legal_tag_properties.LegalTagProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
