# coding: utf-8

"""
    self-managed-osdu

    Rest API Documentation for Self Managed OSDU  # noqa: E501

    OpenAPI spec version: 0.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.file_record import FileRecord  # noqa: E501
from swagger_client.rest import ApiException


class TestFileRecord(unittest.TestCase):
    """FileRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileRecord(self):
        """Test FileRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.file_record.FileRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
