# coding: utf-8

"""
    self-managed-osdu

    Rest API Documentation for Self Managed OSDU  # noqa: E501

    OpenAPI spec version: 0.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import OsduClient
from OsduClient.models.register_ddms import RegisterDdms  # noqa: E501
from OsduClient.rest import ApiException


class TestRegisterDdms(unittest.TestCase):
    """RegisterDdms unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegisterDdms(self):
        """Test RegisterDdms"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OsduClient.models.register_ddms.RegisterDdms()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
