/* 
 * self-managed-osdu
 *
 * Rest API Documentation for Self Managed OSDU
 *
 * OpenAPI spec version: 0.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OsduClient.Api;
using OsduClient.Model;
using OsduClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OsduClient.Test
{
    /// <summary>
    ///  Class for testing FileMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FileMetadataTests
    {
        // TODO uncomment below to declare an instance variable for FileMetadata
        //private FileMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FileMetadata
            //instance = new FileMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileMetadata
        /// </summary>
        [Test]
        public void FileMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FileMetadata
            //Assert.IsInstanceOfType<FileMetadata> (instance, "variable 'instance' is a FileMetadata");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Acl'
        /// </summary>
        [Test]
        public void AclTest()
        {
            // TODO unit test for the property 'Acl'
        }
        /// <summary>
        /// Test the property 'Legal'
        /// </summary>
        [Test]
        public void LegalTest()
        {
            // TODO unit test for the property 'Legal'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Ancestry'
        /// </summary>
        [Test]
        public void AncestryTest()
        {
            // TODO unit test for the property 'Ancestry'
        }

    }

}
