/* 
 * self-managed-osdu
 *
 * Rest API Documentation for Self Managed OSDU
 *
 * OpenAPI spec version: 0.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OsduClient.Api;
using OsduClient.Model;
using OsduClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OsduClient.Test
{
    /// <summary>
    ///  Class for testing RegisterTopicExample
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RegisterTopicExampleTests
    {
        // TODO uncomment below to declare an instance variable for RegisterTopicExample
        //private RegisterTopicExample instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RegisterTopicExample
            //instance = new RegisterTopicExample();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RegisterTopicExample
        /// </summary>
        [Test]
        public void RegisterTopicExampleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RegisterTopicExample
            //Assert.IsInstanceOfType<RegisterTopicExample> (instance, "variable 'instance' is a RegisterTopicExample");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Op'
        /// </summary>
        [Test]
        public void OpTest()
        {
            // TODO unit test for the property 'Op'
        }

    }

}
