{{- $serviceType := .Values.service.type }}
{{- $servicePort := .Values.service.port }}
apiVersion: v1
kind: Service
metadata:
  name: appinsights-statsd
  labels:
    helm.sh/chart: {{ include "osdu-airflow.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: appinsights-statsd
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ $serviceType }}
  ports:
    - port: {{ $servicePort }}
      protocol: UDP
  selector:
    app.kubernetes.io/name: appinsights-statsd
    app.kubernetes.io/instance: {{ .Release.Name }}
