---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-airflow
  namespace: airflow
spec:
  releaseName: osdu-airflow
  dependsOn:
  - name: osdu-base
    namespace: default
  targetNamespace: airflow
  interval: 5m0s
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./charts/osdu-airflow
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    replicaCount: 1
    nameOverride: ""
    fullnameOverride: ""
    service:
      type: ClusterIP
      port: 8125
    image:
      repository: msosdu.azurecr.io

