---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  releaseName: airflow
  targetNamespace: airflow
  interval: 5m0s
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./charts/osdu-airflow
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    ################################################################################
    # Specify KEDA configuration
    #
    keda:
      version_2_enabled: false

    ################################################################################
    # Specify the Ingress Settings
    #
    ingress:
      issuer: letsencrypt-prod-dns
      enableKeyvaultCert: false

    ################################################################################
    # Specify any optional override values
    #
    image:
      repository: msosdu.azurecr.io

    ################################################################################
    # Specify the airflow configuration
    #
    airflow:

      ###################################
      # Kubernetes - Ingress Configs
      ###################################
      ingress:
        enabled: false
        web:
          annotations:
            kubernetes.io/ingress.class: azure/application-gateway
            appgw.ingress.kubernetes.io/request-timeout: "300"
            appgw.ingress.kubernetes.io/connection-draining: "true"
            appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
            cert-manager.io/acme-challenge-type: http01
          path: "/airflow"
          livenessPath: "/airflow/health"
          tls:
            enabled: true
            secretName: osdu-certificate
          precedingPaths:
            - path: "/airflow/*"
              serviceName: airflow-web
              servicePort: 8080

      ###################################
      # Database - External Database
      ###################################
      postgresql:
        enabled: false
      externalDatabase:
        type: postgres
        passwordSecret: "postgres"
        passwordSecretKey: "postgres-password"
        port: 5432
        properties: "?sslmode=require"
        database: airflow

      ###################################
      # Database - Redis Chart
      ###################################
      redis:
        enabled: false
      externalRedis:
        passwordSecret: "redis"
        passwordSecretKey: "redis-password"
        port: 6380

      ###################################
      # Airflow - DAGs Configs
      ###################################
      dags:
        installRequirements: true
        persistence:
          enabled: true
          existingClaim: airflowdagpvc
          subPath: "dags"

      ###################################
      # Airflow - WebUI Configs
      ###################################
      web:
        podLabels:
          aadpodidbinding: "osdu-identity"
        baseUrl: "http://localhost/airflow"

      ###################################
      # Airflow - Worker Configs
      ###################################
      workers:
        podLabels:
          aadpodidbinding: "osdu-identity"
        replicas: 2

      ###################################
      # Airflow - Flower Configs
      ###################################
      flower:
        enabled: false

      ###################################
      # Airflow - Scheduler Configs
      ###################################
      scheduler:
        podLabels:
          aadpodidbinding: "osdu-identity"
        variables: |
          {}

      ###################################
      # Airflow - Common Configs
      ###################################
      airflow:
        image:
          repository: apache/airflow
          tag: 1.10.12-python3.6
          pullPolicy: IfNotPresent
          pullSecret: ""
        config:
          AIRFLOW__SCHEDULER__STATSD_ON: "False"
          AIRFLOW__SCHEDULER__STATSD_HOST: "appinsights-statsd"
          AIRFLOW__SCHEDULER__STATSD_PORT: 8125
          AIRFLOW__SCHEDULER__STATSD_PREFIX: "osdu_airflow"
          AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
          AIRFLOW__CORE__LOGGING_LEVEL: DEBUG
          AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
          AIRFLOW__WEBSERVER__RBAC: "True"
          AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
          AIRFLOW__WEBSERVER__AUTH_BACKEND: "airflow.contrib.auth.backends.password_auth"
          AIRFLOW__API__AUTH_BACKEND: "airflow.contrib.auth.backends.password_auth"
          AIRFLOW__CORE__REMOTE_LOGGING: "True"
          AIRFLOW__CORE__REMOTE_LOG_CONN_ID: "az_log"
          AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "wasb-airflowlog"
          AIRFLOW__CORE__LOGGING_CONFIG_CLASS: "log_config.DEFAULT_LOGGING_CONFIG"
          AIRFLOW__CORE__LOG_FILENAME_TEMPLATE: "{{ run_id }}/{{ ti.dag_id }}/{{ ti.task_id }}/{{ ts }}/{% if dag_run.conf is not none and 'correlation_id' in dag_run.conf %}{{ dag_run.conf['correlation_id'] }}{% else %}None{% endif %}/{{ try_number }}.log"
          AIRFLOW__CELERY__SSL_ACTIVE: "True"
          AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
          AIRFLOW__CORE__PLUGINS_FOLDER: "/opt/airflow/plugins"
          AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 60
        extraEnv:
        - name: CLOUD_PROVIDER
          value: "azure"
        - name: AIRFLOW_VAR_KEYVAULT_URI
          valueFrom:
            configMapKeyRef:
              name: osdu-svc-config
              key: ENV_KEYVAULT
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow
              key: fernet-key
        - name: AIRFLOW_CONN_AZ_LOG
          valueFrom:
            secretKeyRef:
              name: airflow
              key: remote-log-connection
        - name: AIRFLOW_VAR_AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: tenantid
        - name: AIRFLOW_VAR_AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: principal-clientid
        - name: AIRFLOW_VAR_AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: principal-clientpassword
        - name: AIRFLOW_VAR_AAD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: application-appid
        - name: AIRFLOW_VAR_APPINSIGHTS_KEY
          valueFrom:
            secretKeyRef:
              name: central-logging
              key: appinsights
        - name: AIRFLOW_VAR_AZURE_ENABLE_MSI
          value: "false"
        - name: CI_COMMIT_TAG
          value: "v0.11.0"
        - name: AIRFLOW_VAR_ENTITLEMENTS_MODULE_NAME
          value: "entitlements_client"
        - name: AIRFLOW_VAR_CORE__CONFIG__DATALOAD_CONFIG_PATH
          value: "/opt/airflow/dags/configs/dataload.ini"
        - name: AIRFLOW_VAR_CORE__SERVICE__SCHEMA__URL
          value:  "http://schema.osdu-azure.svc.cluster.local/api/schema-service/v1/schema"
        - name: AIRFLOW_VAR_CORE__SERVICE__SEARCH__URL
          value: "http://search.osdu-azure.svc.cluster.local/api/search/v2/query"
        - name: AIRFLOW_VAR_CORE__SERVICE__STORAGE__URL
          value:  "http://storage.osdu-azure.svc.cluster.local/api/storage/v2/records"
        - name: AIRFLOW_VAR_CORE__SERVICE__FILE__HOST
          value: "http://file.osdu-azure.svc.cluster.local/api/file/v2"
        - name: AIRFLOW_VAR_CORE__SERVICE__WORKFLOW__HOST
          value: "http://workflow.osdu-azure.svc.cluster.local/api/workflow"
        - name: AIRFLOW_VAR_CORE__SERVICE__SEARCH_WITH_CURSOR__URL
          value: "http://search.osdu-azure.svc.cluster.local/api/search/v2/query_with_cursor"
        extraConfigmapMounts:
        - name: remote-log-config
          mountPath: /opt/airflow/config
          configMap: airflow-remote-log-config
          readOnly: true
        extraPipPackages: [
          "flask-bcrypt==0.7.1",
          "apache-airflow[statsd]",
          "apache-airflow[kubernetes]",
          "apache-airflow-backport-providers-microsoft-azure==2021.2.5",
          "dataclasses==0.8",
          "google-cloud-storage",
          "python-keycloak==0.24.0",
          "msal==1.9.0",
          "azure-identity==1.5.0",
          "azure-keyvault-secrets==4.2.0",
          "azure-storage-blob",
          "azure-servicebus==7.0.1",
          "toposort==1.6",
          "strict-rfc3339==0.7",
          "jsonschema==3.2.0",
          "pyyaml==5.4.1",
          "requests==2.25.1",
          "tenacity==8.0.1",
          "https://azglobalosdutestlake.blob.core.windows.net/pythonsdk/osdu_api-0.11.0.tar.gz",
          "https://azglobalosdutestlake.blob.core.windows.net/pythonsdk/osdu_airflow-0.0.1.tar.gz"
        ]
        extraVolumeMounts:
        - name: azure-keyvault
          mountPath: "/mnt/azure-keyvault"
          readOnly: true
        - name: dags-data
          mountPath: /opt/airflow/plugins
          subPath: plugins
        extraVolumes:
        - name: azure-keyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault
