/* 
 * self-managed-osdu
 *
 * Rest API Documentation for Self Managed OSDU
 *
 * OpenAPI spec version: 0.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// FileDownloadResponse
    /// </summary>
    [DataContract]
    public partial class FileDownloadResponse :  IEquatable<FileDownloadResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileDownloadResponse" /> class.
        /// </summary>
        /// <param name="signedURL">signedURL.</param>
        public FileDownloadResponse(string signedURL = default(string))
        {
            this.SignedURL = signedURL;
        }
        
        /// <summary>
        /// Gets or Sets SignedURL
        /// </summary>
        [DataMember(Name="SignedURL", EmitDefaultValue=false)]
        public string SignedURL { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FileDownloadResponse {\n");
            sb.Append("  SignedURL: ").Append(SignedURL).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FileDownloadResponse);
        }

        /// <summary>
        /// Returns true if FileDownloadResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of FileDownloadResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FileDownloadResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SignedURL == input.SignedURL ||
                    (this.SignedURL != null &&
                    this.SignedURL.Equals(input.SignedURL))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SignedURL != null)
                    hashCode = hashCode * 59 + this.SignedURL.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
