---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-base
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: f222cf2e-9059-4809-9567-5c02ce6d0163
      resourcegroup: osdu-self-cplcgbgj-wyr2-rg
      identity: osdu-self-cplcgbgj-wyr2-osdu-identity
      identity_id: 27dd1bf5-bfab-4f94-b0a9-d0e84c02bac9
      keyvault: osdu-self-cplcgb-wyr2-kv
      appid: 0fcf2808-d6b3-4569-a2db-61f4a083741d
    image:
      repository: osduselfcplcgbwyr2cr.azurecr.io
