---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-base
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: f222cf2e-9059-4809-9567-5c02ce6d0163
      resourcegroup: osdu-self-cplbech-41n5-rg
      identity: osdu-self-cplbech-41n5-osdu-identity
      identity_id: a60daf56-e682-42c2-b111-e6f233309afb
      keyvault: osdu-self-cplbec-41n5-kv
      appid: 0fcf2808-d6b3-4569-a2db-61f4a083741d
    image:
      repository: osduselfcplbec41n5cr.azurecr.io
