---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: dev-sample
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: f222cf2e-9059-4809-9567-5c02ce6d0163
      resourcegroup: osdu-self-cpldccia-kg8j-rg
      identity: osdu-self-cpldccia-kg8j-osdu-identity
      identity_id: 6faf93b4-2d89-4884-b989-e857521f2ec2
      keyvault: osdu-self-cpldcc-kg8j-kv
      appid: 0fcf2808-d6b3-4569-a2db-61f4a083741d
