---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: entitlement-service
  namespace: osdu-azure
spec:
  values:
    ingress:
      dns: osdu-self-nur-dplbbcbd-kxg3-gw.eastus.cloudapp.azure.com
    configuration:
    - service: entitlements
      repository: osduselfcplbbc1gqpcr.azurecr.io/entitlements
      path: /api/entitlements/v2/*
      probe:
        path: /api/entitlements/v2/_ah/readiness_check
        port: http
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v2/api-docs"
          - "*/swagger-resources"
          - "*/swagger-ui.html"
          - "*/actuator/health"
          - "*/health"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/entitlements/v2/info"
          - "/api/entitlements/v2/swagger-resources/*"
          - "/api/entitlements/v2/webjars/*"
      env:
      - name: spring_application_name
        value: entitlements
      - name: server.servlet.contextPath
        value: /api/entitlements/v2/
      - name: LOGGING_LEVEL
        value: INFO
      - name: server_port
        value: "80"
      - name: service_domain_name
        value: contoso.com
      - name: root_data_group_quota
        value: "5000"
      - name: redis_ttl_seconds
        value: "1"
      - name: partition_service_endpoint
        value: http://partition/api/partition/v1
      - name: azure_istioauth_enabled
        value: "true"
      - name: azure_activedirectory_AppIdUri
        value: "api://b573bfdc-543a-48ef-b1b8-126387b8b4d6"
      - name: azure_paas_podIdentity_isEnabled
        value: "false"
      - name: KEYVAULT_URI
        config:
          name: osdu-svc-config
          key: ENV_KEYVAULT
      - name: aad_client_id
        secret:
          name: active-directory
          key: application-appid
      - name: appinsights_key
        secret:
          name: central-logging
          key: appinsights
