---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: partition-service
  namespace: osdu-azure
spec:
  values:
    ingress:
      dns: osdu-self-dplbech-mrf9-gw.eastus.cloudapp.azure.com
    configuration:
    - service: partition
      repository: osduselfcplbec41n5cr.azurecr.io/partition
      path: /api/partition/v1/*
      probe:
        path: /actuator/health
        port: 8081
        liveness:
          delay: 250
          seconds: 10
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v1/api-docs"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "*/swagger"
          - "*/swagger-ui.html"
          - "*/swagger-resources"
          - "/api/partition/v1/swagger-resources/*"
          - "/api/partition/v1/webjars/*"
          - "*/actuator/health"
          - "*/health"
      env:
      - name: spring_application_name
        value: "partition"
      - name: server.servlet.contextPath
        value: "/api/partition/v1/"
      - name: server_port
        value: "80"
      - name: ACCEPT_HTTP
        value: "true"
      - name: partition_spring_logging_level
        value: "INFO"
      - name: azure_activedirectory_AppIdUri
        value: "api://0fcf2808-d6b3-4569-a2db-61f4a083741d"
      - name: azure_activedirectory_session_stateless
        value: "false"
      - name: azure_paas_podIdentity_isEnabled
        value: "true"
      - name: azure_istioauth_enabled
        value: "true"
      - name: KEYVAULT_URI
        config:
          name: osdu-svc-config
          key: ENV_KEYVAULT
      - name: REDIS_DATABASE
        config:
          name: osdu-svc-config
          key: REDIS_DB_PARTITION
      - name: appinsights_key
        secret:
          name: central-logging
          key: appinsights
      - name: aad_client_id
        secret:
          name: active-directory
          key: application-appid
