---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: self-managed-base
  namespace: osdu-azure
spec:
  values:
    fullnameOverride: osdu-svc
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: f222cf2e-9059-4809-9567-5c02ce6d0163
      resourcegroup: osdu-self-cplcbhcf-zpvw-rg
      identity: osdu-self-cplcbhcf-zpvw-osdu-identity
      identity_id: e323bf22-9c4b-460f-a879-d95d54372b2d
      keyvault: osdu-self-cplcbh-zpvw-kv
      appid: 0fcf2808-d6b3-4569-a2db-61f4a083741d
      oidAuthEnabled: false
    resourceLimits:
      defaultCpuRequests: "100m"
      defaultMemoryRequests: "800Mi"
      defaultCpuLimits: "1000m"
      defaultMemoryLimits: "2Gi"
    identity:
      name: osdu-identity
