---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unit-service
  namespace: osdu-azure
spec:
  values:
    ingress:
      dns: osdu-self-nur-dplbbcbd-kxg3-gw.eastus.cloudapp.azure.com
    configuration:
    - service: unit
      repository: osduselfcplbbc1gqpcr.azurecr.io/unit
      path: /api/unit/*
      probe:
        path: /api/unit/_ah/readiness_check
        port: http
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v2/api-docs"
          - "*/swagger-resources"
          - "*/swagger-ui.html"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/unit/swagger-resources/*"
          - "/api/unit/webjars/*"
          - "*/actuator/health"
          - "*/health"
          - "*/_ah/**"
      pvc:
      - name: unit
        volume: shared-data
      mount:
      - name: shared-data
        path: /mnt/unit_catalogs
      env:
      - name: spring_application_name
        value: unit-service
      - name: server.servlet.contextPath
        value: /api/unit/
      - name: server_port
        value: 80
      - name: ACCEPT_HTTP
        value: true
      - name: ENTITLEMENT_URL
        value: http://entitlements/api/entitlements/v2
      - name: azure_istioauth_enabled
        value: "true"
      - name: KEYVAULT_URI
        config:
          name: osdu-svc-config
          key: ENV_KEYVAULT
      - name: aad_client_id
        secret:
          name: active-directory
          key: application-appid
      - name: appinsights_key
        secret:
          name: central-logging
          key: appinsights
